Repository th-D138/Backend-JobForeigner, pull requests merged in 2025-07, with the labels that each got.

#44 feat : 채용공고 마감 알림 기능 & 채용공고 지원 기능
  src/main/java/kr/ac/kumoh/d138/JobForeigner/global/exception/ExceptionType.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/controller/JobPostController.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/controller/NotificationController.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/domain/ApplicationStatus.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/domain/JobApplication.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/domain/JobPost.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/domain/Notification.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/dto/alarm/NotificationResponseDto.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/repository/JobApplicationRepository.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/repository/NotificationRepository.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/service/CompanyService.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/service/JobPostService.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/job/service/NotificationService.java
Labels: enhancement

#48 공통 예외 응답 추가
  src/main/java/kr/ac/kumoh/d138/JobForeigner/global/exception/ExceptionType.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#46 docs : Member, Resume 스웨거 문서화 추가
  src/main/java/kr/ac/kumoh/d138/JobForeigner/global/config/swagger/SwaggerApiResponses.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/global/exception/ExceptionType.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/member/api/MemberApi.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/member/controller/MemberController.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/resume/api/ResumeApi.java
  src/main/java/kr/ac/kumoh/d138/JobForeigner/resume/controller/ResumeController.java
Labels: documentation

#65 프론트엔드에서 Authorization 헤더를 읽을 수 있도록 수정
  src/main/java/kr/ac/kumoh/d138/JobForeigner/global/config/security/CorsConfig.java
Labels: bug
